---
- name: Install Rails Server
  hosts: servers
  remote_user: ubuntu
  become: yes
  become_method: sudo
  pre_tasks:
    - name: apt-get update
      raw: apt-get update -qq
  roles:
    - common
    - nginx
    - certbot
    - ruby
    - rails
    - monit
    - redis
