---
- name: Install Rails Server
  hosts: servers
  remote_user: ubuntu
  become: yes
  become_method: sudo
  pre_tasks:
    - name: apt-get update
      raw: apt-get update -qq
  roles:
    - common
    - nginx
    - { role: rvm_io.ruby,
        tags: ruby,
        rvm1_rubies: ["{{ ruby_version }}"],
        rvm1_user: 'ubuntu'
      }
    - { role: geerlingguy.nodejs,
        nodejs_npm_global_packages: [],
        nodejs_version: "{{ node_version }}"
      }
    - certbot
    # - ruby
    # - node
    - rails
    - monit
    - redis
